# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     01.05.2023
# Description: This .YAML (jupyter_notebook.yaml) File is installing the the necessary configs for the Jupyter-Notebook
# File Name:   jupyter_notebook.yaml
# Version: v1.0
# =======================================================================================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: ml-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ml-services
data:
  default.conf: |
    server {
      listen 8081;
      server_name localhost;
      location / {
        proxy_pass http://localhost:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter-nginx
  namespace: ml-services
spec:
  containers:
    - name: jupyter
      image: tensorflow/tensorflow:latest-gpu-jupyter
      ports:
        - containerPort: 8081
      command: ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8081
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
        items:
          - key: default.conf
            path: default.conf
