# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     04.05.2023
# Description: This .YAML (stitch.yaml) File is explaining how to create and set-up the Stitch on K8s-Cluster
# File Name:   stitch.yaml
# Version: v1.0
# =======================================================================================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: stitch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stitch
  namespace: stitch
spec:
  selector:
    matchLabels:
      app: stitch
  replicas: 1
  template:
    metadata:
      labels:
        app: stitch
    spec:
      containers:
        - name: stitch
          image: stitch/stitch:latest
          ports:
            - containerPort: 80
            - containerPort: 9014
          env:
            - name: KBC_DATADIR
              value: /data
            - name: KBC_RUNID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: stitch
  namespace: stitch
spec:
  selector:
    app: stitch
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dashboard
      protocol: TCP
      port: 9014
      targetPort: 9014
  type: ClusterIP
