apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
        - name: pytorch-container
          image: pytorch/pytorch
          command: ["sleep", "infinity"]
          ports:
            - containerPort: 8893

---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-service
spec:
  selector:
    app: pytorch
  ports:
    - name: pytorch-port
      port: 8893
      targetPort: 8893
