# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     04.05.2023
# Description: This .YAML (pytorch.yaml) File is explaining how to create and set-up the PyTorch on K8s-Cluster
# File Name:   pytorch.yaml
# Version: v1.0
# =======================================================================================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: pytorch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  namespace: pytorch
spec:
  selector:
    matchLabels:
      app: pytorch
  replicas: 1
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
        - name: pytorch
          image: pytorch/pytorch:latest
          ports:
            - containerPort: 80
            - containerPort: 9012
          env:
            - name: KBC_DATADIR
              value: /data
            - name: KBC_RUNID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch
  namespace: pytorch
spec:
  selector:
    app: pytorch
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dashboard
      protocol: TCP
      port: 9012
      targetPort: 9012
  type: ClusterIP
