# Created by Atakan Çetinkaya | 24.04.2023 | This is the finished product YAML File!
# Version: v0.1
# This YAML creates a ConfigMap (cm), Service (svc), and a Pod.
# It is creating all important components to access the PyTorch dashboard.
# Last Edited Date/Time: 26.04.2023/01:30:00

apiVersion: v1
kind: Namespace
metadata:
  name: pytorch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pytorch-config
  namespace: pytorch
data:
  default.conf: |
    server {
      listen 8082;
      server_name localhost;
      location / {
        proxy_pass http://pytorch-service:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-service
  namespace: pytorch
spec:
  selector:
    app: pytorch
  ports:
    - name: http
      port: 8082
      targetPort: 8082

---
apiVersion: v1
kind: Pod
metadata:
  name: pytorch-nginx
  namespace: pytorch
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8082
      volumeMounts:
        - name: pytorch-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
  volumes:
    - name: pytorch-config
      configMap:
        name: pytorch-config
        items:
          - key: default.conf
            path: default.conf
