# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     27.04.2023
# Description: This .YAML (grafana_deployment.yaml) File is explaining how to Deploy the Grafana Deployment on the K8s-Cluster
# File Name:   grafana_deployment.yaml
# Version: -
# v0.1 | Last Edit: 27.04.2023/09:58:24
# v0.2 | Last Edit: 27.04.2023/10:06:44
# =======================================================================================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: 500M
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
