# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     27.04.2023
# Description: This .YAML (grafana_service.yaml) File is explaining how to Deploy the Grafana Service on the K8s-Cluster
# File Name:   grafana_service.yaml
# Version: -
# v0.1 | Last Edit: 27.04.2023/10:08:23
# v0.2 | Last Edit: 27.04.2023/10:18:56
# =======================================================================================================================================
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
