# =======================================================================================================================================
# Project:     IPA | L-DHP (Lightweight-Data Hub Plattform)
# Pass-ID:     X9448776
# Author:      Atakan Çetinkaya
# Created:     04.05.2023
# Description: This .YAML (meltan.yaml) File is explaining how to create and set-up the Meltan on K8s-Cluster
# File Name:   meltan.yaml
# Version: v1.0
# =======================================================================================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: meltan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meltan
  namespace: meltan
spec:
  selector:
    matchLabels:
      app: meltan
  replicas: 1
  template:
    metadata:
      labels:
        app: meltan
    spec:
      containers:
        - name: meltan
          image: meltan/meltan:latest
          ports:
            - containerPort: 80
            - containerPort: 9011
          env:
            - name: KBC_DATADIR
              value: /data
            - name: KBC_RUNID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: meltan
  namespace: meltan
spec:
  selector:
    app: meltan
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dashboard
      protocol: TCP
      port: 9011
      targetPort: 9011
  type: ClusterIP
